### PR TITLE
Scroll To Top Button

### PR DESCRIPTION
**Pull request by mezmi**
Added 'Scroll To Top' function that injects a [ ▲ TOP ] button into the navbar if TOP > 100px

_This requires the navbar to be fixed to the top as I didn't want to cover up any content_

### CODE REVIEW

**Comment by shu8** [comment]
@enkimatt that's a nice, _invisible_, issue you made there :P

**Comment by mezmi** [comment]
Ahhh crap! I'm honestly still figuring out how this all works.

**Comment by shu8** [comment]
@enkimatt lol no problem! I was saying: before making a pull request for a _new feature_, or even a _bug fix_, just make an [issue](https://guides.github.com/features/issues/) first.

The only reason is, in the future, it helps looking at when new features were added! :) 

But it's not necessary at all! And I'm guilty of not doing so myself :P 

I will merge this, just need to sort out some conflicts :)

**Comment by mezmi** [comment]
@shu8  Okay, cool. I will do that from now on.

**Comment by shu8** [comment]
@enkimatt merged :) 

Make sure you pull the latest version!

and BTW when you add features, please could you add them at the bottom of the `functionsToCall` object? (It's just the way I've been doing it from the beggining)

I seriously need to make a wiki :P

**Comment by mezmi** [comment]
Yeah, sorry about that, I'll all them to the bottom of the list from now on.

**Comment by shu8** [comment]
@enkimatt no problem! Thanks :) I'm making the wiki now :)

**Comment by shu8** [comment]
@enkimatt done: https://github.com/shu8/SE_OptionalFeatures/wiki/Contributing :)

**Pull request merged**
