### PR TITLE
Kbd and bullets

### PR DESCRIPTION
**Pull request by SnoringFrog**
Get rid of the uneeded JS alerts and also fix the id for the bullet button to get that working.

Fixes issue #19 and re-fixes issue #13

### CODE REVIEW

**Comment by shu8** [comment]
(develop version of #22 -- for future reference!)

Thanks @SnoringFrog!

**Comment by shu8** [comment]
I'll have to look into this a bit more, it seems SE has changed this. This is what I see:

screen shot 2015-09-18 at 07 13 14

 So... no merge yet! :(

**Comment by SnoringFrog** [comment]
Aren't those just their standard unordered/ordered list buttons and not the one from the script? I was referring to the extra bullet/unordered list button.

**Comment by SnoringFrog** [comment]
Although I do see that they have their button ids on the `li`s instead of the `span`s. Shouldn't matter for the function of the button (doesn't seem to for my locally modified script), but might be good to change for consistency.

**Comment by shu8** [comment]
You're right... don't know what I was thinking at that time! :/ Merged! :) Thanks for fixing it!

**Pull request merged**
