### PR TITLE
implemented sticky functionality manually to respect fixed topbar

### PR DESCRIPTION
**Pull request by Loxos**
This code change resovles issue #5

### CODE REVIEW

**Comment by shu8** [comment]
@Loxos thank you! It works as far as I can see - so thank you for writing that! I will merge this to dev to test for a few weeks and push to main branch when I think there aren't any bugs. Thanks again!

**Comment by Loxos** [comment]
@shu8 Thanks for accepting my pull request (my first contribution on github ;) )

I think the stickyelement jquery plugin isn't anymore in use now. So I think you could delete this to.

**Comment by shu8** [comment]
@Loxos you're right; done :)

And congrats for your first contribution! :)

**Comment by shu8** [comment]
@Loxos sorry for the trouble but it seems that because we are no longer using a container, the buttons merge with the post contents when scrolling down.

See:
this

I can't think of a way to fix this without adding a container - do you have any ideas?

We might have to go back to using the plugin! :(

**Comment by Loxos** [comment]
@shu8 on which SE page does this error occur for you? At least I can't reproduce this behaviour on SE at the moment...

but we could also just add a suitable margin-left to the content for gaining votebutton space.

**Comment by shu8** [comment]
on all pages... :/ I wonder why that is - do you have any extra userscripts
installed??

**Comment by shu8** [comment]
@Loxos hmm - it seems to work on my other computer. Please bear with me till I check my original computer I experienced this. I'm beginning to think this is a problem with me :/ SORRY! I will check ASAP and get back to you. Sorry again for the (possible) waste of time...

**Comment by shu8** [comment]
@Loxos ok... this is embarassing. It works now. :/ Sorry for the waste of time - but you'll be happy to know that I'm pushing 1.6 DEV to master today! :)

**Pull request merged**
