### PR TITLE
Flag Outcome Times

### PR DESCRIPTION
**Pull request by mezmi**
Added a function to display the time a of a flags outcome, example.

spam – shu8 38 mins ago   helpful **– 34 mins ago**

### CODE REVIEW

**Comment by shu8** [comment]
@enkimatt thanks! added to dev version.

**Comment by shu8** [comment]
@enkimatt BTW did you get that from a feature request on Meta? If so, can you give me the link please so I can link to it in the README. If you didn't, no problem, I'll just add it without a link :)

**Comment by mezmi** [comment]
@shu8 -  No, it wasn't a feature request (that I know of), just something that has been bugging me lately. :)

**Comment by shu8** [comment]
@enkimatt ok, adding to the README now :)

**Comment by mezmi** [comment]
Very cool! :)  I have a few other features I would like to implement, hopefully you don't mind..

**Comment by shu8** [comment]
@enkimatt no problem, but please make separate issues for them first! (and if possible, links to Meta :)

**Comment by mezmi** [comment]
Oh, I will! :)

**Pull request merged**
