### PR TITLE
Added Overall Percentage of Helpful Flags

### PR DESCRIPTION
**Pull request by mezmi**
Added Overall Percentage of Helpful Flags
[Issue](https://github.com/shu8/SE_OptionalFeatures/issues/37)

### CODE REVIEW

**Comment by shu8** [comment]
BTW @enki-code just thought you should know that I updated the script with your updated version at MSO :)

**Comment by mezmi** [comment]
@shu8  I've got a few different variations of that script, let me check which one you have, I might have one that's a little better.  I've also, posted a different version on StackApps. 

https://stackapps.com/questions/6773/flagging-percentages

**Comment by shu8** [comment]
@enki-code nice :) Upvoted! I've edited it again to use your stack apps version :) I like that one because it breaks it down for you...

Thanks!

**Comment by mezmi** [comment]
@shu8  I added you as a contributor to the UserScript I started working on, it's basically SOOF, just written a little differently, check it out and let me know what you think.

**Comment by shu8** [comment]
@enki-code I really like the way it's written - it's easier to read, and the category/feature's thing is a nice touch! 

If you don't mind, would you like to work together and add some of your parts to SOOF? :) Some parts I think SOOF can improve on are UI and the way it's written, which SOX seems to start to solve!

However, if you want to start this as a new project of your own, that's totally fine as well!

**Comment by mezmi** [comment]
@shu8  Yes, let's implement them in SOOF, I just started that more or less as a sandbox.  I think it would be easier for everyone if we just extended what you already have instead of starting another userscript, SOOF is already established :)

**Comment by enki-code** [comment]
You can email me at enki.matt at outlook dot com (gotta love spam bots), that way we don't have to communicate via comments.

**Pull request merged**
